#A docker that sets up an nginx reverse proxy which uses SSL and hosts the server as well.
FROM nginx
#Copy the entire node server into the container (including a couple pointless things).
COPY . /opt/srv
#
